### ISSUE TITLE
allow to use sqlite instead of mysql

### ISSUE THREAD

**Issue by sbarex** [Kapeli/Dash-Annotations#1]
you can use sqlite instead of mysql changing the .env file:

```
DB_DRIVER=sqlite
DB_CONNECTION=sqlite
```

Next you must create a empty file named `storage/database.sqlite` and then executing `artisan migrate`

To work you need to edit the database structure:
field `users.moderator` set default value to `0`
field `identifiers.banned_from_public` set default value to `0`
field `entries.removed_from_public` set default value to `0`
field `teams.access_key` set default value to _`empty string`_
field `entry_team.removed_from_team` set default value to `0`

**Comment by Kapeli** [comment]
My server uses mysql so that's what it's set up for. You can use whatever database you want though, just make the changes locally.

If you need any changes made to better support sqlite, please open a pull request.

**Comment by Kapeli** [comment]
I've made some changes to make the README a bit more straightforward. Please let me know if I broke anything.

I removed the results for the `Get the database credentials` step as I didn't think they're really needed.

**Comment by Kapeli** [comment]
I've also removed the `ext-redis` requirement from `composer.json`...
