### ISSUE TITLE
Has annotation server been tried on Linux?

### ISSUE THREAD

**Issue by DavidJameson** [Kapeli/Dash-Annotations#4]
Upgraded to 3.x    Interested in running my own annotation server but I'd like it to live on a Linux box rather than my desktop.
I had never heard of the two toolkits before (and it took quite a bit of reading to figure out that Lumens was just yet another web app framework) so before I waste a lot of time, I figured I'd just ask you.

Cheers,
David Jameson

**Comment by Kapeli** [comment]
annotations.kapeli.com (the default server) runs on a Linux box (Ubuntu).
