### ISSUE TITLE
Add semver support

### ISSUE THREAD

**Issue by outcoldman** [Kapeli/Dash-Annotations#5]
Could you please add releases or maybe track changes with tags so it will be easier for people use annotations on their own servers? At current moment it is hard to understand when you really need to do upgrade and when don't, when some staff can be broken and when don't.

In the best will be good to support http://semver.org

**Comment by Kapeli** [comment]
Will do. Thanks for the feedback!

Most of the changes are really really small, but I'll make sure to tag a release once in a while. My best recommendation would be to just keep up with master. I don't think I'll break anything and if I break anything, I'd probably break my own server too and will promptly fix it with a new commit.
