### ISSUE TITLE
Couldn't connect to annotations server

### ISSUE THREAD

**Issue by CiTroNaK** [Kapeli/Dash-Annotations#8]
Hi,
I've followed the installation guide and installed a custom Annotation Server at for example dash.mydomain.com. At browser I can see `{"status":"error","message":"Not logged in"}`.

I told it to Dash

```
defaults write com.kapeli.dashdoc AnnotationsCustomServer "https://dash.mydomain.com"
```

After Dash app restart I can see only this error message `Couldn't connect to annotations server`.

I am using HTTPS with valid certificate.

Is there anything I've done wrong?

Thank you.

**Comment by Kapeli** [comment]
Can you tell me what the server is? Have you tried without https if it works? Is the certificate self-issued?

**Comment by CiTroNaK** [comment]
It is working only with https. Certificate is from startssl.com. Please write me to my email (you can find it in my profile here). I will send you what you want for finding the problem and solution. Thank you.
