### ISSUE TITLE
PostgreSQL Support

### ISSUE THREAD

**Issue by CiTroNaK** [Kapeli/Dash-Annotations#9]
Hi,
I tried to use it with PostreSQL and got errors. Could you please add support for PostreSQL database? 

Thank you.

**Comment by Kapeli** [comment]
This is not something I'm willing to support as I have no need for it. Sorry! Feel free to open a pull request that adds support for PostgreSQL though.

**Comment by CiTroNaK** [comment]
Ok, thanks. I thought it should be easy to use Lumen with PostgreSQL - http://lumen.laravel.com/docs/database - it is supported by default. I am not PHP developer so I hope you will someday find time to test it and tweak it for the PostgreSQL support :-)
